version: '3.9'
services:
  react-app:
    build: ./react
    volumes:
      - ./react:/usr/src/app
    command: >
      sh -c "cd react-app && npm start"
    ports:
      - "3000:3000"
  nginx:
    image: nginx:latest
    container_name: nginx
    ports: 
      - 8000:80
    volumes:
      - ./react/react-app/build:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - react-app